version: '3'
services:
  portfolio-server:
      container_name: portfolio-server
      image: "portfolio-server:1.0.0"
      ports:
       - "8080:8080"
      networks:
      - backend
  portfolio:
      container_name: portfolio
      image: "portfolio:1.0.0"
      ports:
       - "80:80"
      networks:
       - backend
 
networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge